config/routes.rb
Rails.application.routes.draw do
  get 'urls/showlongurl' => 'urls#show_long_url'
  get 'urls/longurl' => 'urls#long_url'
  post 'urls/getlongurl' => 'urls#get_long_url'
  get 'dailyreport/index' => 'dailyreport#index'
  get 'urls/error' => 'urls#error'
  get 'urls/search' => 'urls#search'
  post  'urls/getlongurl' => 'urls#get_long_url'
  devise_for :users
  root 'welcome#index'
  require 'sidekiq/web'  
  mount Sidekiq::Web, :at => '/sidekiq' 

  post 'shorten-url' => 'urls#create'

  get 'short-url' => 'urls#get_long_url'
  resources :urls
  
end

app/models/url.rb
class Url < ApplicationRecord
  include Elasticsearch::Model
  include Elasticsearch::Model::Callbacks
  
  validates :long_url, url: true , uniqueness: true,presence: true 
  validates :short_url , presence: true
  validates :domain_name , presence: true 
  after_create :generate_daily_report_in_background


  settings index: {
  number_of_shards: 1,
  number_of_replicas: 0,
  analysis: {
    analyzer: {
      pattern: {
        type: 'pattern',
        pattern: "\\s|_|-|\\.",
        lowercase: true
      },
      trigram: {
        tokenizer: 'trigram'
      }
    },
    tokenizer: {
      trigram: {
        type: 'ngram',
        min_gram: 3,
        max_gram: 1000,
        token_chars: ['letter', 'digit']
      }
    }
    } 
  } do
  mapping do
      indexes :short_url, type: 'text', analyzer: 'english' do
      indexes :keyword, analyzer: 'keyword'
      indexes :pattern, analyzer: 'pattern'
      indexes :trigram, analyzer: 'trigram'
      end
      indexes :long_url, type: 'text', analyzer: 'english' do
      indexes :keyword, analyzer: 'keyword'
      indexes :pattern, analyzer: 'pattern'
      indexes :trigram, analyzer: 'trigram'
      end
    end
  end

  def self.custom_search(query , field)
    field = field + ".trigram"
    urls = self.__elasticsearch__.search(
    {
     query: {
      bool: {
       must: [{
        term: {
         "#{field}":"#{query}"
        }
       }]
      }
     }
  }).records
  return urls
  end

  def generate_daily_report_in_background
    HardWorker.perform_async
  end

  def as_indexed_json(options={})
    as_json(only: [:long_url, :short_url, :domain_name])
  end

  def pass_parameter(url)
    url.short_url = url_shortner(url.long_url)
    short_domain = domain_shortner(url.domain_name)
    return url , short_domain
  end
  def self.caching_implementation_for_short_Url(short_url)
      Rails.cache.fetch("#{short_url}",expires_in: 15.minutes) do
      Url.find_by_short_url(short_url)
    end
   end 
   def self.long_url(params)
      shorturl = params[:short_url]
      start = 6
      length = shorturl.length
      shorturl = shorturl[start..length]                                                        #parsing_short_url 
      long_url = Url.caching_implementation_for_short_Url(shorturl)
   end

  private
    def url_shortner(long_url)
      low = 1
      high = 7
      encoded_short_url_1 = Digest::MD5.hexdigest long_url

      encoded_short_url_2 = Digest::MD5.hexdigest encoded_short_url_1

      short_url = encoded_short_url_2[low..low+high]
      itr = 2 

      while itr+high <= encoded_short_url_2.length && Url.find_by_short_url(short_url).present? do
        short_url = encoded_short_url_2[itr..itr + high]
        itr += 1
      end
      if Url.where(short_url:  short_url).first.present?
        return "error"
      end 
      return short_url
    end
 
    def domain_shortner(domain_name)
      short_domain = Domain.find_by_long_domain(domain_name).short_domain
      return short_domain
    end

end

app/controllers/urls_controller.rb
class UrlsController < ApplicationController
  include UrlsHelper
=begin
 **Author:** saurabh kaushal <br/>
 **Common Name:** index page of our system <br />
 **Request Type:** GET <br />
 **Route :** '/welcome/index' <br />
 **Authentication Required:** None <br />
=end
  def index

  	@url = Url.new

  end

=begin
 **Author:** saurabh kaushal <br/>
 **Common Name:** post method for shotening url <br />
 **Request Type:** post <br />
 **Route :** '/urls' <br />
 **Authentication Required:** None <br />
 ** Request format
 {
   long_url: "https://www.proptiger.com/" (mandatory)
   domain_name: "proptiger"               (mandatory)
 }
 **Responset Format**
 Success(status : 200)
 {
   short_url: "pr.tg/c56760c7"
 }
=end

  def create
    long_url = params[:url][:long_url]
    domain_name = params[:url][:domain_name]
    url = Url.find_by_long_url(params[:url][:long_url])
    render_response_for_create_url(url,domain_name,long_url)
  end

=begin
 **Author:** saurabh kaushal <br/>
 **Common Name:** view page for short url on front-end <br />
 **Request Type:** GET <br />
 **Route :** '/urls/show' <br />
 **Authentication Required:** None <br />
=end
  def show

    @short_url = params[:short_url]

  end
=begin
 **Author:** saurabh kaushal <br/>
 **Common Name:** conversion of short_url to long_url front end<br />
 **Request Type:** GET <br />
 **Route :** '/urls/long_url' <br />
 **Authentication Required:** None <br />
=end
  def long_url

    @url = Url.new

  end

=begin
 **Author:** saurabh kaushal <br/>
 **Common Name:** conversion of short_url to long_url <br />
 **Request Type:** POST <br />
 **Route :** '/urls/getlongurl' <br />
 **Authentication Required:** None <br />
 ** Request format
 {
   short_url: "pr.tg/c56760c7" (mandatory)
 }
 **Responset Format**
 Success(status : 200)
 {
    long_url: "https://www.proptiger.com/"
 }
=end


  def get_long_url

    if(params[:short_url] == "")
      flash[:message]="Please Enter Url"
      redirect_to urls_longurl_path
    else
      long_url = Url.long_url(params)
      render_reponse_for_long_url(long_url)
      
    end
  end

=begin
 **Author:** saurabh kaushal <br/>
 **Common Name:** showing long_url on front end <br />
 **Request Type:** GET <br />
 **Route :** '/urls/showlongurl' <br />
 **Authentication Required:** None <br />
=end
  def show_long_url
    @long_url = params[:long_url]
  end

=begin
 **Author:** saurabh kaushal <br/>
 **Common Name:** elastic search on query <br />
 **Request Type:** GET <br />
 **Route :** '/urls/search' <br />
 **Authentication Required:** None <br />
=end
  def search
    query = params[:urls_search].presence && params[:urls_search][:query]
    if query
      @urls = Url.custom_search(params[:urls_search][:query],params[:urls_search][:field])
    end
  end

  private

    def url_params
      params.require(:url).permit(:long_url , :domain_name)
    end

end

app/helpers/urls_helper.rb
module UrlsHelper
  #rendering reponse for create method
  def render_response_for_create_url(url,domain_name,long_url)
    domain = Domain.check_presence_of_domain(domain_name)
    domain_from_long_url = (Domainatrix.parse(long_url)).domain
    puts "dflu" 
    puts domain_from_long_url
    puts "dn"
    puts domain_name
    if domain.present?
      puts 'inside'
      respond_to do |format|
        if url.present? && domain_from_long_url == domain_name
          format.html {
            flash[:message] = "long url with same value already present and shorturl is: " +  domain.short_domain + '/' + url.short_url 
            redirect_to urls_path
          } 
          format.json {
            render json: {
              "message" => "successful",
              "status" => "200,ok" ,
              "short_url" =>  domain.short_domain + '/' + url.short_url
              },status: :ok
            }
        elsif url.present? && domain_from_long_url != domain_name
          format.html {
            flash[:message] = "wrong input"  
            redirect_to urls_path
          } 
          format.json {
            render json: {
              "message" => "wrong input",
              },status: :bad_request
            }
        else
          url = Url.new(url_params)
          @url , short_domain = url.pass_parameter(url)
          if @url.short_url == 'error'
            format.html {
              flash[:message] = "sorry, Unable to convert"
              redirect_to urls_path 
            } 
            format.json {
              render json: {
                "message" => "error",
                "status" => "500 , Internal server error"
              } ,status: :internal_server_error
            }
          elsif domain_from_long_url == domain_name && @url.save 
            puts 'here'
            @url.short_url = domain.short_domain + "/" + @url.short_url
            format.html {
              redirect_to url_path(id: @url , short_url: @url.short_url)
            }
            format.json { 
              render json: {
                "message" => "successful",
                "status" => "200,ok",
                "shorturl"=>  @url.short_url
              } ,status: :ok
            }
         
          else
          
            format.html {
              flash[:message] = "wrong input"
              render 'urls/index'
            }
            format.json  {
              render json: {
                "message" => "please input in correct format ",
                "status" => "400,Bad Request"
                },status: :bad_request
            }
          end
        end
      end
    else
      respond_to do |format|
        format.html {
          flash[:message] = "Currently,given domain is not available with us. first have a domain" 
          redirect_to urls_path 
        } 
        format.json {
          render json: {
            "message" => "Given Domain is not available",
            "status" => "400,Bad Request"
          },status: :bad_request 
        }
      end
    end 
	end

  #rendering response for get_long_url method 

  def render_reponse_for_long_url(long_url)

    respond_to do |format|
        if long_url.present?
          format.html {
            redirect_to urls_showlongurl_path(long_url: long_url.long_url)
          }
          format.json { 
            render  json: {
              "message" => "successful",
              "status" => "200,ok",
              "long_url"=> long_url.long_url
            },status: :ok 
          }
        
        else
          format.html {
            flash[:message] = "Not Found"
            redirect_to urls_longurl_path
          }
          format.json {
            render  json: {
            "message" => "Not found",
            "status" => "404"
            } , status: :not_found
          }
        end  
      end
  end
  

end

app/views/urls/index.html.erb
<center> 
  <h1>
    Generate Short URL
  </h1>

  <%= form_with(model: @url, local: true) do |form| %>
    <% if @url.errors.any? %>
      <div id="error_explanation">
        <h2>
          <%= pluralize(@url.errors.count, "error") %> prohibited
          this form from being saved:
        </h2>
        <ul>
          <% @url.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
    <p>
      Long Url <%= form.text_field :long_url %><br>
      
    </p>
 
   <p>
      Domain <%= form.text_field :domain_name %><br>
      
    </p>
    <h3>
      <%= form.submit "create"%>
    </h3>
 
  <% end %>


  <h1>
    <%=link_to 'logout',destroy_user_session_path , method: :delete  %> </br> </br>

    <%=link_to 'back',  root_path %>

  </h1>
</center>

app/views/urls/long_url.html.erb
<center>
	<h1> Get Long Url</h1>
	<%= form_with url: 'getlongurl'  do |form| %>
	<p>
    	Short Url <%= form.text_field :short_url %><br>
    </p>
 	<p>
    	<%= form.submit "Get_Long_Url" %>
  	</p>
 	<% end %>

	<h1> <%= link_to 'logout' ,destroy_user_session_path , method: :delete%> </br>

	<%=link_to 'back',  root_path %> </h1>

</center>

app/views/urls/longurl.html.erb
<center>
	<h1> Get Long Url</h1>
	<%= form_with url: 'getlongurl'  do |form| %>
	<p>
    	Short Url <%= form.text_field :short_url %><br>
    </p>
 	<p>
    	<%= form.submit "Get_Long_Url" %>
  	</p>
 	<% end %>

	<h1> <%= link_to 'logout' ,destroy_user_session_path , method: :delete%> </br>

	<%=link_to 'back',  root_path %> </h1>

</center>

app/views/urls/search.html.erb
<head>
  <style>
  table, th, td {
    border: 1px solid black;
    border-collapse: collapse;
  }

  th, td {
    padding: 15px;
  }
  </style>
</head>
<body>
  <h1>Elastic search for Urls</h1>

  <%= form_for :urls_search, url: urls_search_path, method: :get do |form| %>
  <%= form.select :field, ['long_url', 'short_url']%> </br> 
  <%= form.text_field :query, value: params[:urls_search].presence && params[:urls_search][:query] %>
  <%= form.submit 'Search' %>
  <% end %>

  <% unless @urls.nil? %>
  <% if @urls.empty? %>
    <h2>No posts found matching your query.</h2>
  <% else %>
    <h2>Search results</h2>

    <table style="width: 100%;">
      <thead>
         <tr>
           <th>Long Url</th>
           <th>Short Url</th>
           <th>domain Name</th>
         </tr>
      </thead>

      <tbody>
        <% @urls.each do |url| %>
          <tr>
            <td><%= url.long_url %></td>
            <td><%= url.short_url %></td>
            <td><%= url.domain_name %></td>
          </tr>
        <% end %>
      <tbody>
    </table>
  <% end %>
  <% end %>

  <%=link_to 'back',  root_path %>

</body>

app/views/urls/show.html.erb
<center>
	<p> Short Url:  </p>
	
	<h3><%= @short_url %> </h3> </br>

	<h1> <%=link_to 'back', urls_path  %> </br> </br> 

	<%=link_to 'logout',destroy_user_session_path , method: :delete  %>

	<%=link_to 'cross check', urls_longurl_path %> </h1>
</center>

app/views/urls/show_long_url.html.erb
<center>
	<p> Long Url : </p>  
	<h3> <%= @long_url %>  </h3> </br> 

	<h1><%= link_to 'back' , urls_longurl_path %> </br>

	<%= link_to 'logout' , destroy_user_session_path , method: :delete %> </br> <h1>

</center >

app/views/urls/showlongurl.html.erb
<center>
	<p> Long Url is: </p>  
	<h3> <%= @var %>  </h3> </br> 

	<h1><%= link_to 'back' , urls_longurl_path %> </br>

	<%= link_to 'logout' , destroy_user_session_path , method: :delete %> </br> <h1>

</center >